"""empty message

Revision ID: 170a29f81d19
Revises: cd4832893054
Create Date: 2021-03-20 01:20:38.735417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170a29f81d19'
down_revision = 'cd4832893054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_property', 'filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_property', sa.Column('filename', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
